[package]
name = "uiohook-sys"
version = "0.1.0"
edition = "2018"
links = "uiohook"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
cmake = "0.1"
bindgen = "0.59.0"